### ISSUE TITLE
README: 2 links to scripts/deploy.sh are dead

### ISSUE THREAD

**Issue by knbknb** [felipecrs/dev-ubuntu#4]
Your Vagrant Image might be a good starting point for my project, so I might check it out from Vagrantcloud. Besides, your shellscripts contain a nice bag of tricks. Thanks!

However, the README  at this time contains 2 links to a nonexistant `scripts/deploy.sh` file. Please update or remove the links. I think it's now `ci/deploy.sh`. 

And the base image is not `hashicorp/bionic64`, it's `bento/ubuntu-18.04/`

It would also helpful if you mentioned in the README how large the image actually is (approximately, in Gigabytes).

**Comment by felipecrs** [comment]
Hi!

Thank you for your feedback, it helps a lot! Also take a look on [my-ubuntu1804-4dev](https://github.com/felipecassiors/my-ubuntu1804-4dev), there you can find some tricks aimed for refined user/computer/environment settings. 

I fixed the links in README, it was indeed `ci/deploy.sh`. Also the base box reference. 

For the box size, I created a very simple (and in very early stage: currently you can't select which provider to get the size, not a problem for this box today since it only have `virtualbox`) badge to it, since there wasn't one already. I plan to enhance it over time, so other people may also use it.

[![Vagrant box size](https://img.shields.io/endpoint?url=https://runkit.io/felipecassiors/vagrant-box-size/branches/master/felipecassiors/ubuntu1804-4dev)](https://app.vagrantup.com/felipecassiors/boxes/ubuntu1804-4dev)
Source code: https://runkit.com/felipecassiors/vagrant-box-size
